FULL_SCREEN_MODE = False
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 900
WINDOW_TITLE = 'Инопланетное вторжение'
BG_COLOR = (230, 230, 230)

SHIP_SPEED = 1.5

BULLET_SPEED = 5
BULLET_WIDTH = 5
BULLET_HIGHT = 15
BULLET_COLOR = (60, 60, 60)
BULLETS_ALLOWED = 10
BULLET_KILL_BY_ALIEN = True

ALIEN_SPEED = 1.0
ALIEN_KILL_BY_BULLET = True
FLEET_DOWN_SPEED = 10
